# Generated by Django 5.1.2 on 2024-10-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_add_default_dimensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingdimension',
            options={'ordering': ['created_at'], 'verbose_name': '处理维度', 'verbose_name_plural': '处理维度'},
        ),
        migrations.RemoveIndex(
            model_name='processingdimension',
            name='processing__type_8f6065_idx',
        ),
        migrations.RemoveIndex(
            model_name='processingdimension',
            name='processing__is_defa_f4dbd5_idx',
        ),
        migrations.RemoveField(
            model_name='processingdimension',
            name='order',
        ),
        migrations.RemoveField(
            model_name='processingdimension',
            name='type',
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='维度描述'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认维度'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='name',
            field=models.CharField(max_length=100, verbose_name='维度名称'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='processingdimension',
            table=None,
        ),
    ]
