# Generated by Django 5.1.2 on 2024-10-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_processingdimension_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingdimension',
            name='dimension_type',
            field=models.CharField(choices=[('cleaning', '清洗维度'), ('labeling', '标注维度')], default='cleaning', max_length=20, verbose_name='维度类型'),
        ),
    ]
