# Generated by Django 5.1.2 on 2024-10-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_processingdimension_dimension_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingdimension',
            options={'ordering': ['type', 'order', 'name'], 'verbose_name': '处理维度', 'verbose_name_plural': '处理维度'},
        ),
        migrations.RemoveField(
            model_name='processingdimension',
            name='dimension_type',
        ),
        migrations.AddField(
            model_name='processingdimension',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='processingdimension',
            name='type',
            field=models.CharField(choices=[('cleaning', '数据清洗'), ('labeling', '数据标注')], default='cleaning', max_length=20, verbose_name='维度类型'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='维度描述'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认'),
        ),
        migrations.AlterField(
            model_name='processingdimension',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='processingdimension',
            index=models.Index(fields=['type'], name='processing__type_8f6065_idx'),
        ),
        migrations.AddIndex(
            model_name='processingdimension',
            index=models.Index(fields=['is_default'], name='processing__is_defa_f4dbd5_idx'),
        ),
        migrations.AlterModelTable(
            name='processingdimension',
            table='processing_dimensions',
        ),
    ]
