# Generated by Django 5.1.2 on 2024-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_processingdimension_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='type',
            field=models.CharField(choices=[('cleaning', '数据清洗'), ('labeling', '数据标注'), ('chat', '聊天对话')], max_length=20),
        ),
    ]
