# Generated by Django 5.1.2 on 2024-11-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_systemprompt_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='维度描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '清洗维度',
                'verbose_name_plural': '清洗维度',
                'db_table': 'cleaning_dimensions',
            },
        ),
        migrations.CreateModel(
            name='LabelingDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='维度名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='维度描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '标注维度',
                'verbose_name_plural': '标注维度',
                'db_table': 'labeling_dimensions',
            },
        ),
        migrations.DeleteModel(
            name='ProcessingDimension',
        ),
        migrations.AlterModelOptions(
            name='systemprompt',
            options={'verbose_name': '系统提示词', 'verbose_name_plural': '系统提示词'},
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='content',
            field=models.TextField(help_text='系统提示词的具体内容', verbose_name='提示词内容'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='is_default',
            field=models.BooleanField(default=False, help_text='每种类型只能有一个默认提示词', verbose_name='是否默认'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='json_schema',
            field=models.TextField(blank=True, help_text='用于规范化输出的JSON格式示例，标注类型必填', null=True, verbose_name='JSON格式范例'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='type',
            field=models.CharField(choices=[('cleaning', '数据清洗'), ('labeling', '数据标注'), ('chat', '聊天对话')], max_length=20, verbose_name='提示词类型'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
