# Generated by Django 5.1.2 on 2024-11-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_systemprompt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemprompt',
            options={'verbose_name': '系统提示词', 'verbose_name_plural': '系统提示词'},
        ),
    ]
